// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBICmnQGMtbdiDwVza1dZOL-TxC1l6-X4Q',
    appId: '1:319872514950:android:f8f67f45497a60ff170a07',
    messagingSenderId: '319872514950',
    projectId: 'flutter-net-9e73b',
    databaseURL: 'https://flutter-net-9e73b-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-net-9e73b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRAqUBbPiB1vA0OC5jL979oExFSVzpX0Q',
    appId: '1:319872514950:ios:a8b100d99ef71c09170a07',
    messagingSenderId: '319872514950',
    projectId: 'flutter-net-9e73b',
    databaseURL: 'https://flutter-net-9e73b-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-net-9e73b.appspot.com',
    iosClientId: '319872514950-hrig3m3ghqge7pn7svsaro61ks56l850.apps.googleusercontent.com',
    iosBundleId: '12',
  );
}
